runtime: python27
api_version: 1
threadsafe: true

# IMPORTANTE: service es el servicio al que se va a realizar el deployment.
# Dejar en default para el front de administración
# quitar el gato y cambiar por gastos-front o prov-front para los otros módulos

service: gastos-front

# Google App Engine's cache default expiration time is 10 minutes. It's suitable for most Production
# scenarios, but a shorter TTL may be desired for Development and QA, as it allows us to see a fresh
# code in action just a minute after the deployment.
default_expiration: 60s

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|svg|json)(|\.map))$
    static_files: dist/gastos-front/\1
    upload: dist/gastos-front/(.*)(|\.map)

  - url: /(.*)
    static_files: dist/gastos-front/index.html
    upload: dist/gastos-front/index.html


skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
 # - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE